float crossing1 = 0;
float crossing2 = 0;
float px1 = 0;
float py1 = 0;
float pz1 = 0;
float px2 = 0;
float py2 = 0;
float pz2 = 0;
float charge1 = 0;
float charge2 = 0;
float dedx1 = 0;
float dedx2 = 0;
float dca3dxy1 = 0;
float dca3dxy2 = 0;
float track1_mvtx_states = 0;
float track2_mvtx_states = 0;
float mass1 = 0;
float mass2 = 0;

float cosThetaReco = 0;
float projected_pair_dca = 0;
float projected_pathlength_x = 0;
float projected_pathlength_y = 0;
float projected_path_length_z = 0;
float invariant_pt = 0;
float invariant_mass = 0;
float projected_mom1_x = 0;
float projected_mom1_y = 0;
float projected_mom1_z = 0;
float projected_mom2_x = 0;
float projected_mom2_y = 0;
float projected_mom2_z = 0;

ntp->SetBranchAddress("crossing1", &crossing1);
ntp->SetBranchAddress("crossing2", &crossing2);
ntp->SetBranchAddress("projected_mom1_x", &projected_mom1_x);
ntp->SetBranchAddress("projected_mom1_y", &projected_mom1_y);
ntp->SetBranchAddress("projected_mom1_z", &projected_mom1_z);
ntp->SetBranchAddress("projected_mom2_x", &projected_mom2_x);
ntp->SetBranchAddress("projected_mom2_y", &projected_mom2_y);
ntp->SetBranchAddress("projected_mom2_z", &projected_mom2_z);
ntp->SetBranchAddress("px1", &px1);
ntp->SetBranchAddress("py1", &py1);
ntp->SetBranchAddress("pz1", &pz1);
ntp->SetBranchAddress("px2", &px2);
ntp->SetBranchAddress("py2", &py2);
ntp->SetBranchAddress("pz2", &pz2);
ntp->SetBranchAddress("charge1", &charge1);
ntp->SetBranchAddress("charge2", &charge2);
//ntp->SetBranchAddress("dedx1", &dedx1);
//ntp->SetBranchAddress("dedx2", &dedx2);
ntp->SetBranchAddress("dca3dxy1", &dca3dxy1);
ntp->SetBranchAddress("dca3dxy2", &dca3dxy2);
//ntp->SetBranchAddress("track1_mvtx_states", &track1_mvtx_states);
//ntp->SetBranchAddress("track2_mvtx_states", &track2_mvtx_states);
//ntp->SetBranchAddress("mass1", &mass1);
//ntp->SetBranchAddress("mass2", &mass2);
ntp->SetBranchAddress("projected_pair_dca", &projected_pair_dca);
ntp->SetBranchAddress("projected_pathlength_x", &projected_pathlength_x);
ntp->SetBranchAddress("projected_pathlength_y", &projected_pathlength_y);
ntp->SetBranchAddress("invariant_pt", &invariant_pt);
ntp->SetBranchAddress("invariant_mass", &invariant_mass);
ntp->SetBranchAddress("cosThetaReco", &cosThetaReco);
